version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Listing directory contents..."
      - ls -la
      - echo "Validating template..."
      - aws cloudformation validate-template --template-body file://search-gateway.yaml
      - echo "Packaging template..."
      - aws cloudformation package --template-file search-gateway.yaml --s3-bucket artifacts-bucket-gl-esanchez --output-template-file search.yaml
      - echo "Showing packaged template..."
      - cat search.yaml

artifacts:
  files:
    - search-gateway.yaml
    - search.yaml
    - lambda_function.py
    - search_page.py