AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchgateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: 'Search gateway function for OpenSearch integration'
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::197444073346:role/search-engine-cloudformation-role'